server:
  port: 0
spring:
  application:
    name: item-ws
  boot:
    admin:
      client:
        url:
        - http://admin:admin@localhost:8761/admin
  zipkin:
    base-url: http://localhost:9411
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3315/hr
    username: root
    password: sanjay1304
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'   